import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from '@/components/Header/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  // Variaveis
  const data = new Date()

  // Rendering
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          min-h-screen flex flex-col items-center justify-start 
          p-4 md:p-10 gap-4 /* Reduzi o padding de p-20 para p-4/p-10 para ganhar espaço */
        `}
      >
        <Header />
        
        {/* CORREÇÃO AQUI: 
            Removi as classes restritivas (md:w-2/3 lg:w-1/2 xl:w-1/3)
            Adicionei max-w-7xl para permitir uma largura ampla e confortável para grelhas de cards
        */}
        <main className="bg-blue-200 p-6 rounded-2xl min-h-[70vh] w-full max-w-7xl shadow-xl">
          {children}
        </main>
        
        <footer className="text-gray-500 text-sm font-medium">
          DIW, {data.getFullYear()}
        </footer>
      </body>
    </html>
  );
}